sudo: required
dist: trusty
language: go
go:
  - 1.8.3
script:
  - make && make pretest && make test && make integration-test && make integration-test-container &&
    if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
      make deploy;
      make integration-test-deploy;
    fi
notifications:
  email:
    on_success: always
    on_failure: always
